=== AliaksandrKrukouski/Java/Task4/data/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.example.org/flowers" 
		xmlns:tns="http://www.example.org/flowers" 
		elementFormDefault="qualified">

    <element name="flowers"> 
		<complexType> 
			<sequence>
				<element name="flower" type="tns:flowerType" minOccurs="1" maxOccurs="unbounded" />
			</sequence>	
        </complexType>
	<element>
	
	<complexType name="flowerType">
		<sequence> 
			<element name="name" type="ID"/>
			<element name="solid">
				<simpleType>
					<restriction base="string">
						<enumiration value="Podzol"></enumiration>
						<enumiration value="Chernozem"></enumiration>
						<enumiration value="Sand"></enumiration>
						<enumiration value="Clay"></enumiration>
					</restriction>
				</simpleType>
			</element>
			<element name="origin">
				<simpleType>
					<restriction base="string">
						<pattern value="[A-Za-z ]"/>
					</restriction>
				</simpleType>	
			</element>	
			<element name="visual" type="tns:visualType"/>
			<element name="tips" type="tns:tipsType"/>
		</sequence>
	</complexType>
	
	<complexType name="visualType">
		<sequence>
			<element name="stalkColor" type="tns:colorType">  
			<element name="leafColor" type="tns:colorType"> 
			<element name="length">
				<complexType>
					<restriction base="integer">
						<xs:minInclusive value = "1"/>
						<xs:minInclusive value = "100"/> 						
					</restriction>
					<atribute name="measure" type="tns:lengthType" use="optional" default="Centimeter">	
				<complexType>	
			</element>
		</sequence>
	</complexType>
	
	<simpleType name="colorType">
		<restriction base="string">
			<enumeration value="Brown"/>
			<enumeration value="Green"/>
			<enumeration value="Red"/>
			<enumeration value="Yellow"/>
			<enumeration value="Purple"/>
		</restriction>
	</simpleType>

    <simpleType name="lengthType">
		<restriction base="string">
			<enumeration value="Centimeter"/>
			<enumeration value="Meter"/>
		</restriction>
	</simpleType>	
	
	<complexType name="tipsType">
		<sequence>
			<element name="temperature">
				<complexType>
					type="tns:tempType">
				<complexType>			
			</element>
			<element name="light">
				<simpleType>
					<restriction base="string">
						<enumeration value="Y"/>
						<enumeration value="N"/>
					</restriction>
				</simpleType>	
			</element>	
			<element name="water" type="tns:waterType"/> 
		</sequence>
	</complexType>
	
	
	
</schema>

=== AliaksandrKrukouski/Java/Task4/data/flowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns="http://www.example.org/flowers" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://www.example.org/flowers flowers.xsd">
	<flower>
		<name>Rose</name>
		<solid>Chernozem</solid>
		<origin>Italy</origin>
		<visual>
			<stalkColor>Green</stalkColor>
			<leafColor>Red</leafColor>
			<length measure="Meter">2</length>
		</visual>
		<tips>
			<temperature measure="Celsius">25</temperature>
			<light>Y</light>
			<water measure="Litre" frequency="Week">1</water>	
		</tips>
		<multiplying>Stalk</multiplying>
	</flower>
	<flower>
		<name>Tulips</name>
		<solid>Clay</solid>
		<origin>The Netherland</origin>
		<visual>
			<stalkColor>Green</stalkColor>
			<leafColor>Yellow</leafColor>
			<length measure="Meter">1</length>
		</visual>
		<tips>
			<temperature measure="Celsius">18</temperature>
			<light>Y</light>
			<water measure="Mililitre" frequency="Day">500</water>	
		</tips>
		<multiplying>Bulb</multiplying>
	</flower>
	<flower>
		<name>Orchidaceae</name>
		<solid>Podzol</solid>
		<origin>India</origin>
		<visual>
			<stalkColor>Green</stalkColor>
			<leafColor>Purple</leafColor>
			<length measure="Centimeter">50</length>
		</visual>
		<tips>
			<temperature measure="Fahrenheit">86</temperature>
			<light>Y</light>
			<water measure="Litre" frequency="Day">1</water>	
		</tips>
		<multiplying>Seeds</multiplying>
	</flower>
</flowers>
